# Generated by Django 5.2.4 on 2025-07-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sana",
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(),
        ),
    ]
