# Generated by Django 5.2.4 on 2025-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="holati",
        ),
        migrations.AddField(
            model_name="post",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(),
        ),
    ]
