# Generated by Django 5.2.4 on 2025-07-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_post_holati_post_amount_alter_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
