# Generated by Django 5.2.4 on 2025-07-23 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_post_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "ovqat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transport",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "salomatlik",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "boshqa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("izoh", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
