# Generated by Django 5.2.4 on 2025-07-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_dailyexpense_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyexpense",
            name="year",
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
